driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/ruby-test']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.14.89

platforms:
  - name: windows-i386
    driver:
      box: mwrock/Windows2016

suites:
  - name: default
    run_list: ruby_test_build::default
